### ISSUE TITLE
Menuの実装場所をConsoleUtilsからMenuUtilsへ移動する。

### ISSUE THREAD

**Issue by ZenryokuService** [ZenryokuService/ObjectOrientedPrograming#21]
# MenuUtilsの作成
メニュー処理をConsoleUtilsから移動する。

**Comment by ZenryokuService** [comment]
## 2022/02/17
武器の装備を実装中、下記のエラーが出た。

```
formula: (POW + WEV) * (1 + (0.1 * JLV))
conv: (POW + 0) * (1 + (0.1 * 0))Unknown function or variable 'POW' at pos 1 in expression '(POW + 0) * (1 + (0.1 * 0))'
net.objecthunter.exp4j.tokenizer.UnknownFunctionOrVariableException: Unknown function or variable 'POW' at pos 1 in expression '(POW + 0) * (1 + (0.1 * 0))'
	at net.objecthunter.exp4j.tokenizer.Tokenizer.parseFunctionOrVariable(Tokenizer.java:177)
	at net.objecthunter.exp4j.tokenizer.Tokenizer.nextToken(Tokenizer.java:116)
	at net.objecthunter.exp4j.shuntingyard.ShuntingYard.convertToRPN(ShuntingYard.java:46)
	at net.objecthunter.exp4j.ExpressionBuilder.build(ExpressionBuilder.java:188)
	at jp.zenryoku.rpg.data.RpgFormula.formula(RpgFormula.java:50)
	at jp.zenryoku.rpg.charactors.players.PlayerCharactor.setMainWepon(PlayerCharactor.java:76)
	at jp.zenryoku.rpg.util.MenuUtils.selectEquipMent(MenuUtils.java:100)
	at jp.zenryoku.rpg.util.MenuUtils.printMenu(MenuUtils.java:60)
	at jp.zenryoku.rpg.TextRpgGameEngine.run(TextRpgGameEngine.java:68)
```
