### ISSUE TITLE
PARAM_CONFIG に対してカテゴリ・マスタを作成する。

### ISSUE THREAD

**Issue by ZenryokuService** [ZenryokuService/ObjectOrientedPrograming#22]
# ユーザーが自由なシステム定義を行えるように
ゲームブックを作成するうえで、必要になる要素をカテゴリ化してパラメータ定義を行えるようにする。

＜カテゴリ・マスタ＞
| カテゴリID | カテゴリ名 | 用途・説明 | 読み方 |
| ------------  | ------------- | ------------- | -------- |
| MNY | 通貨 | ゲームブックの世界で使用する通貨 | マネー|
| ATK | 物理攻撃力 | 武器等の物理的な攻撃力を示す | アタック |
| DEF | 物理防御力 | 武器等に対する物理的な防御力を示す | ディフェンス |
| MPW | 魔法威力 | まほう・じゅつなどの効果値 | マジックパワー |
| MAT | 魔法・術攻撃力 | 魔法・術などの効力を示す。式= (かしこさ + きようさ+カリスマ) / 3  + 魔法威力| マジック・アタック |
| MDE | 魔法・術などの攻撃に対する耐性。式= (かしこさ + きようさ + すばやさ) / 3 + 魔よけ力 | 魔法防御力 | マジックディフェンス |
| PLY | プレーヤーステータスに追加する項目、攻撃力や防御力などの拡張に使用する| プレーヤオプション |
|STO|ステータス異常拡張|毒やマヒ、石化などステータス異常の定義を行う|

＜ユーザー定義のサンプル＞
| カテゴリID | カテゴリ名 | 記号 | 用途・説明 |
| ------------  | ------------- | ---- | ------------- |
| MNY | ドル | DOL | ゲームブック内の通貨、USA国の通貨とする |
| MNY | 円 | YEN | ゲームブック内の通貨、日本国の通貨とする |
| ATK | 物理攻撃力 | PNT | 日本刀での攻撃力 |
| ATK | 物理攻撃力 | PNC | 体術での攻撃力 |
|PLY|武器攻撃力|WEV|装備することで攻撃力(ATK)を上げることができる|
|PLY|防具防御力|DEV|装備することで防御力(DEF)を上げることができる|
|STO|ステータス異常|STN|石化、プレーヤーは動けなくなりその場にずっといる事になる|

**Comment by ZenryokuService** [comment]
PARAM_CONFIGにデフォルト値を追加する必要がある。
nullは**exp4j**で変換できない。
```
formula: (POW + WEV) * (1 + (0.1 * JLV))
Key: POW, AGI, INT, DEX, KSM, EVR, MAT, ITN, ITM, WEP, ARV, WEV, ITV, MDE, MPW, JLV, DEF, CST, TSM, MAG, TEC, FRC, ATK, ARM, BPK, 
conv: (1 + null) * (1 + (0.1 * null))Unknown function or variable 'null' at pos 5 in expression '(1 + null) * (1 + (0.1 * null))'
net.objecthunter.exp4j.tokenizer.UnknownFunctionOrVariableException: Unknown function or variable 'null' at pos 5 in expression '(1 + null) * (1 + (0.1 * null))'
	at net.objecthunter.exp4j.tokenizer.Tokenizer.parseFunctionOrVariable(Tokenizer.java:177)
	at net.objecthunter.exp4j.tokenizer.Tokenizer.nextToken(Tokenizer.java:116)
	at net.objecthunter.exp4j.shuntingyard.ShuntingYard.convertToRPN(ShuntingYard.java:46)
	at net.objecthunter.exp4j.ExpressionBuilder.build(ExpressionBuilder.java:188)
	at jp.zenryoku.rpg.data.RpgFormula.formula(RpgFormula.java:63)
	at jp.zenryoku.rpg.charactors.players.PlayerCharactor.setMainWepon(PlayerCharactor.java:80)
	at jp.zenryoku.rpg.util.MenuUtils.selectEquipMent(MenuUtils.java:100)
	at jp.zenryoku.rpg.util.MenuUtils.printMenu(MenuUtils.java:60)
	at jp.zenryoku.rpg.TextRpgGameEngine.run(TextRpgGameEngine.java:68)
```
